version: '3.8'

services:
  web:
    build: ./
    command: python playground/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./playground/:/usr/src/playground
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=playground
      - POSTGRES_PASSWORD=#1Sunshine
      - POSTGRES_DB=playground_dev

volumes:
  postgres_data:

